# Generated by Django 4.2.3 on 2023-09-08 12:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutgoingLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_num', models.CharField(max_length=7, verbose_name="Log's number")),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Полето трябва да съдържа поне 2 букви')], verbose_name='Title')),
                ('recipient', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Полето трябва да съдържа поне 2 букви')], verbose_name='Recipient')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='outgoing_doc_files', verbose_name='Document File')),
                ('signatory_profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_profiles.profile')),
            ],
        ),
    ]
