# Generated by Django 4.2.3 on 2023-07-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outgoing_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoinglogmodel',
            name='signatory_name',
            field=models.CharField(choices=[('Иван Иванов', 'Иван Иванов'), ('Иван Стоянов', 'Иван Стоянов'), ('Лачезар Янчев', 'Лачезар Янчев')], default='Not Present', max_length=70),
        ),
        migrations.AddField(
            model_name='outgoinglogmodel',
            name='signatory_position',
            field=models.CharField(default='Not Present', max_length=70),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outgoinglogmodel',
            name='document_img',
            field=models.ImageField(blank=True, null=True, upload_to='outgoing_doc_img'),
        ),
    ]
