# Generated by Django 4.2.3 on 2024-03-15 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Полето трябва да съдържа поне 2 букви')], verbose_name='Contract Type')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralContractsLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_num', models.IntegerField(verbose_name="Log's number")),
                ('sub_log_num', models.IntegerField(blank=True, null=True, verbose_name="Sub Log's number")),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Полето трябва да съдържа поне 2 букви')], verbose_name='Title')),
                ('creator_user', models.CharField(max_length=150, verbose_name='Creator User')),
                ('first_document_file', models.FileField(blank=True, null=True, upload_to='gen_contracts_doc_files', verbose_name='First Document File')),
                ('second_document_file', models.FileField(blank=True, null=True, upload_to='gen_contracts_doc_files', verbose_name='Second Document File')),
                ('third_document_file', models.FileField(blank=True, null=True, upload_to='gen_contracts_doc_files', verbose_name='Third Document File')),
                ('concerned_employees', models.ManyToManyField(blank=True, to='user_profiles.employeepositionsmodel', verbose_name='Concerned Employees')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contracts_log.contracttypesmodel', verbose_name='Contract type')),
            ],
        ),
        migrations.CreateModel(
            name='FreelanceLectureContractsLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_num', models.IntegerField(verbose_name="Log's number")),
                ('sub_log_num', models.IntegerField(blank=True, null=True, verbose_name="Sub Log's number")),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Полето трябва да съдържа поне 2 букви')], verbose_name='Title')),
                ('creator_user', models.CharField(max_length=150, verbose_name='Creator User')),
                ('first_document_file', models.FileField(blank=True, null=True, upload_to='freelance_lecture_contracts_doc_files', verbose_name='First Document File')),
                ('second_document_file', models.FileField(blank=True, null=True, upload_to='freelance_lecture_contracts_doc_files', verbose_name='Second Document File')),
                ('third_document_file', models.FileField(blank=True, null=True, upload_to='freelance_lecture_contracts_doc_files', verbose_name='Third Document File')),
                ('concerned_employees', models.ManyToManyField(blank=True, to='user_profiles.employeepositionsmodel', verbose_name='Concerned Employees')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contracts_log.contracttypesmodel', verbose_name='Contract type')),
            ],
        ),
        migrations.CreateModel(
            name='FreelanceContractsLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_num', models.IntegerField(verbose_name="Log's number")),
                ('sub_log_num', models.IntegerField(blank=True, null=True, verbose_name="Sub Log's number")),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Полето трябва да съдържа поне 2 букви')], verbose_name='Title')),
                ('creator_user', models.CharField(max_length=150, verbose_name='Creator User')),
                ('first_document_file', models.FileField(blank=True, null=True, upload_to='freelance_contracts_doc_files', verbose_name='First Document File')),
                ('second_document_file', models.FileField(blank=True, null=True, upload_to='freelance_contracts_doc_files', verbose_name='Second Document File')),
                ('third_document_file', models.FileField(blank=True, null=True, upload_to='freelance_contracts_doc_files', verbose_name='Third Document File')),
                ('concerned_employees', models.ManyToManyField(blank=True, to='user_profiles.employeepositionsmodel', verbose_name='Concerned Employees')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contracts_log.contracttypesmodel', verbose_name='Contract type')),
            ],
        ),
        migrations.CreateModel(
            name='EducationContractsLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_num', models.IntegerField(verbose_name="Log's number")),
                ('sub_log_num', models.IntegerField(blank=True, null=True, verbose_name="Sub Log's number")),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Полето трябва да съдържа поне 2 букви')], verbose_name='Title')),
                ('creator_user', models.CharField(max_length=150, verbose_name='Creator User')),
                ('first_document_file', models.FileField(blank=True, null=True, upload_to='training_contracts_doc_files', verbose_name='First Document File')),
                ('second_document_file', models.FileField(blank=True, null=True, upload_to='training_contracts_doc_files', verbose_name='Second Document File')),
                ('third_document_file', models.FileField(blank=True, null=True, upload_to='training_contracts_doc_files', verbose_name='Third Document File')),
                ('concerned_employees', models.ManyToManyField(blank=True, to='user_profiles.employeepositionsmodel', verbose_name='Concerned Employees')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contracts_log.contracttypesmodel', verbose_name='Contract type')),
            ],
        ),
    ]
