# Generated by Django 4.2.3 on 2023-08-09 10:58

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Името трябва да съдържа поне 2 букви'), core.validators.name_cyrillic_letters_and_hyphens_validator], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Фамилията трябва да съдържа поне 2 букви'), core.validators.name_cyrillic_letters_and_hyphens_validator], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(2, 'Длъжността трябва да съдържа поне 2 букви'), core.validators.position_field_validator], verbose_name='Position'),
        ),
    ]
